### ISSUE TITLE
BalancedTimeplusDataSourceITest test case failed

### ISSUE THREAD

**Issue by lizhou1111** [timeplus-io/timeplus-native-jdbc#25]
I set the user name and password(both proton and system account) but i still can't create database
```
[INFO] Running com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest
2024-06-19 19:11:58 [main] INFO io/timeplus-io/proton:latest - Creating container for image: ghcr.io/timeplus-io/proton:latest
2024-06-19 19:11:58 [main] INFO io/timeplus-io/proton:latest - Container ghcr.io/timeplus-io/proton:latest is starting: 8ca9f3ffbae8fbb297283b7510bfc612ff46729df8027d674504f80ea901dbda
2024-06-19 19:11:58 [main] INFO io/timeplus-io/proton:latest - Waiting for database connection to become available at jdbc:timeplus://localhost:34375/default using query 'SELECT 1'
2024-06-19 19:11:59 [main] DEBUG TimeplusStatement - close Statement
2024-06-19 19:11:59 [main] INFO io/timeplus-io/proton:latest - Container ghcr.io/timeplus-io/proton:latest started in PT1.356729S
2024-06-19 19:11:59 [main] INFO io/timeplus-io/proton:latest - Container is started (JDBC URL: jdbc:timeplus://localhost:34375/default)
2024-06-19 19:11:59 [main] DEBUG BalancedTimeplusDataSource - Pinging disabled url: jdbc:timeplus://localhost:34375
2024-06-19 19:11:59 [main] DEBUG BalancedTimeplusDataSource - Url is alive now: jdbc:timeplus://localhost:34375
2024-06-19 19:11:59 [main] DEBUG TimeplusStatement - close Statement
2024-06-19 19:11:59 [main] DEBUG BalancedTimeplusDataSource - Pinging disabled url: jdbc:timeplus://not.existed.url:34375
2024-06-19 19:11:59 [main] WARN BalancedTimeplusDataSource - Url is dead now: jdbc:timeplus://not.existed.url:34375
2024-06-19 19:11:59 [main] DEBUG TimeplusStatement - close Statement
2024-06-19 19:11:59 [main] DEBUG BalancedTimeplusDataSource - Pinging disabled url: jdbc:timeplus://not.existed.url:34375
2024-06-19 19:11:59 [main] WARN BalancedTimeplusDataSource - Url is dead now: jdbc:timeplus://not.existed.url:34375
2024-06-19 19:11:59 [main] DEBUG BalancedTimeplusDataSource - Pinging disabled url: jdbc:timeplus://localhost:34375
2024-06-19 19:11:59 [main] DEBUG BalancedTimeplusDataSource - Url is alive now: jdbc:timeplus://localhost:34375
2024-06-19 19:11:59 [main] DEBUG TimeplusStatement - close Statement
[ERROR] Tests run: 6, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 2.628 s <<< FAILURE! - in com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest
[ERROR] testSingleDatabaseConnection  Time elapsed: 0.014 s  <<< ERROR!
com.github.timeplus.exception.TimeplusSQLException: 
DB::ExceptionDB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE DATABASE ON test.*. Stack trace:


        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testSingleDatabaseConnection$0(BalancedTimeplusDataSourceITest.java:43)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testSingleDatabaseConnection$4(BalancedTimeplusDataSourceITest.java:43)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.testSingleDatabaseConnection(BalancedTimeplusDataSourceITest.java:42)
Caused by: com.github.timeplus.exception.TimeplusSQLException: 
DB::ExceptionDB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE DATABASE ON test.*. Stack trace:


        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testSingleDatabaseConnection$0(BalancedTimeplusDataSourceITest.java:43)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testSingleDatabaseConnection$4(BalancedTimeplusDataSourceITest.java:43)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.testSingleDatabaseConnection(BalancedTimeplusDataSourceITest.java:42)

[ERROR] testDualDatabaseConnection  Time elapsed: 0.016 s  <<< ERROR!
com.github.timeplus.exception.TimeplusSQLException: 
DB::ExceptionDB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE DATABASE ON test.*. Stack trace:


        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testDualDatabaseConnection$5(BalancedTimeplusDataSourceITest.java:64)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testDualDatabaseConnection$6(BalancedTimeplusDataSourceITest.java:64)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.testDualDatabaseConnection(BalancedTimeplusDataSourceITest.java:63)
Caused by: com.github.timeplus.exception.TimeplusSQLException: 
DB::ExceptionDB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE DATABASE ON test.*. Stack trace:


        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testDualDatabaseConnection$5(BalancedTimeplusDataSourceITest.java:64)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testDualDatabaseConnection$6(BalancedTimeplusDataSourceITest.java:64)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.testDualDatabaseConnection(BalancedTimeplusDataSourceITest.java:63)

[ERROR] testWorkWithEnabledUrl  Time elapsed: 0.009 s  <<< ERROR!
com.github.timeplus.exception.TimeplusSQLException: 
DB::ExceptionDB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE DATABASE ON test.*. Stack trace:


        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testWorkWithEnabledUrl$17(BalancedTimeplusDataSourceITest.java:129)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testWorkWithEnabledUrl$18(BalancedTimeplusDataSourceITest.java:129)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.testWorkWithEnabledUrl(BalancedTimeplusDataSourceITest.java:128)
Caused by: com.github.timeplus.exception.TimeplusSQLException: 
DB::ExceptionDB::Exception: default: Not enough privileges. To execute this query it's necessary to have grant CREATE DATABASE ON test.*. Stack trace:


        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testWorkWithEnabledUrl$17(BalancedTimeplusDataSourceITest.java:129)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.lambda$testWorkWithEnabledUrl$18(BalancedTimeplusDataSourceITest.java:129)
        at com.github.timeplus.jdbc.BalancedTimeplusDataSourceITest.testWorkWithEnabledUrl(BalancedTimeplusDataSourceITest.java:128)

```

**Comment by Jasmine-ge** [comment]
closed by #34
