### ISSUE TITLE
Invalid version for SerializationLowCardinality key column.. Stack trace:

### ISSUE THREAD

**Issue by kuiliu88** [timeplus-io/timeplus-native-jdbc#35]
### Environment

- OS version: Ubuntu
- JDK version:
- ClickHouse Server version: 
- ClickHouse Native JDBC version:
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
Exception in thread "main" com.timeplus.exception.TimeplusSQLException: DB::ExceptionDB::Exception: Invalid version for SerializationLowCardinality key column.. Stack trace:


	at com.timeplus.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:33)
	at com.timeplus.protocol.Response.readFrom(Response.java:35)
	at com.timeplus.client.NativeClient.receiveResponse(NativeClient.java:207)
	at com.timeplus.client.NativeClient.receiveEndOfStream(NativeClient.java:158)
	at com.timeplus.jdbc.TimeplusConnection.sendInsertRequest(TimeplusConnection.java:294)
	at com.timeplus.jdbc.statement.TimeplusPreparedInsertStatement.executeBatch(TimeplusPreparedInsertStatement.java:155)
	at examples.BatchQuery.main(BatchQuery.java:47)
	Suppressed: java.sql.SQLException: Call getSampleBlock before insert.
		at com.timeplus.misc.Validate.isTrue(Validate.java:41)
		at com.timeplus.jdbc.TimeplusConnection.sendInsertRequest(TimeplusConnection.java:289)
		at com.timeplus.jdbc.statement.TimeplusPreparedInsertStatement.close(TimeplusPreparedInsertStatement.java:168)
		at examples.BatchQuery.main(BatchQuery.java:33)
[BatchQuery 2.java.zip](https://github.com/user-attachments/files/16245289/BatchQuery.2.java.zip)

```

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
